#!/bin/bash
clear

# Change to the directory containing the python script
# cd
#cd ~/Desktop/Coding_Files/PythonProjects/GAMES/castlecardgame

# Activate the virtual environment
source venv/bin/activate

# Run the python script
python3 main.py
