#!/bin/bash
clear

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# echo "Script directory: $SCRIPT_DIR"

# Change to the directory containing the python script
cd $SCRIPT_DIR

# Activate the virtual environment
#source venv/bin/activate

# Run the python script
python3 main.py
